(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,h="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var n={da:!0},p={};try{p.__proto__=n;l=p.da;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var q=k,goog=goog||{},r=this||self,t=Date.now||function(){return+new Date},u=function(a,b){a=a.split(".");var c=r;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};var v=function(){this.A={}};v.prototype.add=function(a,b){a="string"===typeof a?a:a.getString();this.A[a]||(this.A[a]=[]);this.A[a].push(b)};var w=function(a){var b=[],c="object"==typeof gwd&&"GwdId"in gwd,d;for(d in a.A)b.push(c?new gwd.GwdId(d):d);return b},x=function(a,b){return b?a.A["string"===typeof b?b:b.getString()]||[]:[]};var y=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},z=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},A=function(a){if(z(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&z(a))return a;return null};var B=function(a,b){this.j=a;this.ea=b;this.H=this.M.bind(this)};B.prototype.observe=function(a){if(a.nodeType==Node.ELEMENT_NODE)for(var b=w(this.j),c=0;c<b.length;c++){var d=C(b[c]);if(d&&y(a,d)){var e=x(this.j,b[c]);if(e)for(var f=0;f<e.length;f++)d.addEventListener(e[f].event,this.H,!1)}}};B.prototype.M=function(a){this.ea(a)};var C=function(a){return"string"===typeof a?document.getElementById(a):a.getElement(document)};var D=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d};var F=function(){this.$=""};F.prototype.toString=function(){return"SafeScript{"+this.$+"}"};F.prototype.g=function(a){this.$=a};(new F).g("");var G=function(){this.ba=""};G.prototype.toString=function(){return"SafeStyle{"+this.ba+"}"};G.prototype.g=function(a){this.ba=a};(new G).g("");var H=function(){this.aa=""};H.prototype.toString=function(){return"SafeStyleSheet{"+this.aa+"}"};H.prototype.g=function(a){this.aa=a};(new H).g("");var I=function(){this.Z=""};I.prototype.toString=function(){return"SafeHtml{"+this.Z+"}"};I.prototype.g=function(a){this.Z=a};(new I).g("<!DOCTYPE html>");(new I).g("");(new I).g("<br>");Object.freeze&&Object.freeze([]);var J=function(a,b){var c=(c=r.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):t();a={label:a,type:9,value:c};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var K={},L=!1,M=!1;K.V=function(a){L||(L=!0,J("11",a))};K.qa=function(a){M||(M=!0,J("12",a))};K.ra=function(a,b,c){var d=b;d=void 0===d?r:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===c?0:c,value:d},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};K.reset=function(a){M=L=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};u("gwd.rumUtil",K);u("gwd.rumUtil.logContentLoading",K.V);
u("gwd.rumUtil.logContentRendered",K.qa);u("gwd.rumUtil.logTimingEvent",K.ra);u("gwd.rumUtil.reset",K.reset);var N=function(){var a=HTMLElement.call(this)||this;a.S=a.ka.bind(a);a.K=a.ma.bind(a);a.T=a.la.bind(a);a.D=a.ja.bind(a);a.C=a.ha.bind(a);a.F=D.bind(null,"expandfinish",a);a.B=D.bind(null,"collapsefinish",a);a.R=a.ia.bind(a);a.o=a.pa.bind(a);a.H=a.M.bind(a);a.X=a.na.bind(a);a.ca=a.oa.bind(a);a.i=null;a.c=null;a.w=!1;a.v=!1;a.N=[];a.u=!1;a.J=!1;a.s=null;a.l=!1;a.G=!1;a.I=window.innerHeight>=window.innerWidth?1:2;a.b=null;a.h=null;a.U=!1;return a},O=HTMLElement;N.prototype=h(O.prototype);
N.prototype.constructor=N;if(q)q(N,O);else for(var P in O)if("prototype"!=P)if(Object.defineProperties){var Q=Object.getOwnPropertyDescriptor(O,P);Q&&Object.defineProperty(N,P,Q)}else N[P]=O[P];g=N.prototype;
g.connectedCallback=function(){var a=this;this.U||(this.J=this.hasAttribute("fullscreen"),document.body.style.opacity="0",this.U=!0);Enabler.addEventListener(studio.events.StudioEvent.EXPAND_START,this.D);Enabler.addEventListener(studio.events.StudioEvent.COLLAPSE_START,this.C);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_START,this.D);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_START,this.C);Enabler.addEventListener(studio.events.StudioEvent.EXPAND_FINISH,
this.F);Enabler.addEventListener(studio.events.StudioEvent.COLLAPSE_FINISH,this.B);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.F);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.B);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_DIMENSIONS,this.R);window.addEventListener("resize",this.ca,!1);(0,K.V)(window);setTimeout(function(){a.a=a.querySelector("gwd-pagedeck");a.a.addEventListener("pagetransitionend",a.X,!1);
a.b=document.getElementById(a.getAttribute("data-provider"));a.h=document.querySelector("gwd-data-binder");var b=a.querySelector("gwd-metric-configuration"),c=new v;if(b){b=Array.prototype.slice.call(b.getElementsByTagName("gwd-metric-event"));for(var d=0;d<b.length;d++){var e=b[d],f=e.getAttribute("source");if(f){var m=e.getAttribute("exit");e={event:e.getAttribute("event"),sa:e.getAttribute("metric")||m,fa:e.hasAttribute("cumulative"),exit:m};c.add(R(f),e)}}}a.j=c;a.W=new B(a.j,a.H)},0)};
g.disconnectedCallback=function(){Enabler.removeEventListener(studio.events.StudioEvent.INIT,this.S);Enabler.removeEventListener(studio.events.StudioEvent.VISIBLE,this.K);Enabler.removeEventListener(studio.events.StudioEvent.PAGE_LOADED,this.T);Enabler.removeEventListener(studio.events.StudioEvent.EXPAND_START,this.D);Enabler.removeEventListener(studio.events.StudioEvent.COLLAPSE_START,this.C);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_START,this.D);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_START,
this.C);Enabler.removeEventListener(studio.events.StudioEvent.EXPAND_FINISH,this.F);Enabler.removeEventListener(studio.events.StudioEvent.COLLAPSE_FINISH,this.B);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.F);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.B);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_DIMENSIONS,this.R);this.a.removeEventListener("pagetransitionend",this.X,!1);window.removeEventListener("resize",
this.ca,!1);this.b&&this.i&&this.b.removeEventListener("ready",this.i);this.h&&this.c&&this.h.removeEventListener("bindingfinished",this.c);Enabler.removeEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.o,!1);window.removeEventListener("message",this.o,!1)};g.initAd=function(){this.u=!1;var a=this.S;Enabler.removeEventListener(studio.events.StudioEvent.INIT,a);Enabler.addEventListener(studio.events.StudioEvent.INIT,a);Enabler.isInitialized()&&a()};
g.exit=function(a,b,c,d,e){c=void 0===c?!1:c;d=void 0===d?!0:d;Enabler.exit(a,b);d&&S(this);c&&this.goToPage(e)};g.exitOverride=function(a,b,c,d,e){c=void 0===c?!1:c;d=void 0===d?!0:d;Enabler.exitOverride(a,b);d&&S(this);c&&this.goToPage(e)};g.incrementCounter=function(a,b){Enabler.counter(a,b)};g.startTimer=function(a){Enabler.startTimer(a)};g.stopTimer=function(a){Enabler.stopTimer(a)};g.reportManualClose=function(){Enabler.reportManualClose()};
g.M=function(a){var b=a.target,c=R(b),d=c+": "+a.type;a:{var e=x(this.j,c);for(var f=0;f<e.length;f++)if(e[f].event==a.type){e=e[f];break a}e=void 0}e.exit&&a.detail&&a.detail.url?(d=c+": "+e.exit,a.detail["exit-id"]&&(d=a.detail["exit-id"]),b="",null!=a.detail["product-index"]&&(b=a.detail["product-index"]),this.b&&0==(this.b.getAttribute("gwd-schema-id")||"").indexOf("dynamic_remarketing")?(c=a.detail["action-event"],e={},c&&(e.clickX=c.clientX||c.changedTouches[0].clientX,e.clickY=c.clientY||c.changedTouches[0].clientY),
Enabler.dynamicExit(d,a.detail.url,b,void 0,e)):Enabler.exitOverride(d,a.detail.url),a.detail.handled=!0,a.detail.collapse&&this.goToPage()):(a=A(b))&&a.gwdIsActive()&&this.incrementCounter(e.sa||d,e.fa)};
g.ka=function(){var a=this;Enabler.removeEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.o,!1);window.removeEventListener("message",this.o,!1);Enabler.isServingInLiveEnvironment()?Enabler.addEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.o,!1):window.addEventListener("message",this.o,!1);var b=function(){if(a.hasAttribute("polite-load")){var d=a.T;Enabler.isPageLoaded()?d():Enabler.addEventListener(studio.events.StudioEvent.PAGE_LOADED,d)}else d=a.K,Enabler.isVisible()?
d():Enabler.addEventListener(studio.events.StudioEvent.VISIBLE,d)};if(this.J){var c=function(d){a.s=!!d.supported;a.s&&D("fullscreensupport",a);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_SUPPORT,c);b()};Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_SUPPORT,c);Enabler.queryFullscreenSupport()}else b()};
g.ma=function(a){var b=this;if(this.u)this.b&&this.P(null);else{var c;a&&(c=a.detail);var d=this.ua.bind(this,c);this.b&&(d=this.ga.bind(this,d));if(this.J){Enabler.setResponsiveExpanding(!0);var e=function(f){b.G=f;d()};Enabler.loadModule(studio.module.ModuleId.GDN,function(){var f=studio.sdk.gdn.getConfig();f.isInCreativeToolsetContext()?f.isInterstitial(e):d()})}else d()}};g.la=function(){var a=this.K;Enabler.isVisible()?a():Enabler.addEventListener(studio.events.StudioEvent.VISIBLE,a)};
g.ga=function(a){this.b?(this.i&&this.b.removeEventListener("ready",this.i),this.i=this.P.bind(this,a),this.b.isDataLoaded()&&this.i(),this.b.addEventListener("ready",this.i)):a()};
g.P=function(a){var b=!!a;if(this.h){this.c&&(this.h.removeEventListener("bindingfinished",this.c),this.c=null);var c=this.b.getData();c&&(b=this.a.getElementsBySelector("*"),b=b.concat(this.a.getPages()),this.h.bindData(c,b)?this.Y(a):(this.c=this.Y.bind(this,a),this.h.addEventListener("bindingfinished",this.c)),b=!1)}b&&a()};
g.Y=function(a){this.c&&(this.h.removeEventListener("bindingfinished",this.c),this.c=null);if(this.u){var b=document.getElementsByTagName("gwd-text-helper");0<b.length&&b[0].refitAll()}D("dynamicelementsready",this);a&&a()};g.ua=function(a){this.u||(this.u=!0,document.body.style.opacity="",D("adinitialized",this,a),this.G?(a=this.a.getPage(this.a.findPageIndexByAttributeValue("expanded",!0)),this.goToPage(a.id)):this.goToPage())};
g.goToPage=function(a,b,c,d,e){var f=this.a.getPage(this.a.currentIndex);if(a=a?this.a.getPage(a):this.a.getDefaultPage()){var m=!!f&&!!a&&!this.w&&!this.G&&!f.hasAttribute("expanded")&&a.hasAttribute("expanded");f=!!f&&!!a&&!this.v&&!this.G&&f.hasAttribute("expanded")&&!a.hasAttribute("expanded");m&&this.v||f&&this.w||((this.f=a.id,b&&(this.m={transition:b,duration:c,easing:d,direction:e}),m)?this.J&&!1!==this.s?this.s&&(this.l=!0,Enabler.requestFullscreenExpand()):Enabler.requestExpand():f?this.l?
Enabler.requestFullscreenCollapse():Enabler.requestCollapse():(this.v=this.w=!1,this.L()))}};g.ja=function(){D("expandstart",this);this.s?(this.l=!0,Enabler.finishFullscreenExpand()):Enabler.finishExpand();if(!this.f){var a=this.a.getPage(this.a.findPageIndexByAttributeValue("expanded",!0));a&&(this.f=a.id)}a=this.a.getPage(this.a.currentIndex);this.w=!!a&&this.f!=a.id;window.setTimeout(this.L.bind(this),30)};
g.ha=function(){D("collapsestart",this);this.l?(Enabler.finishFullscreenCollapse(),this.l=!1):Enabler.finishCollapse();this.f||(this.reportManualClose(),this.f=this.a.getDefaultPage().id);var a=this.a.getPage(this.a.currentIndex);this.v=!!a&&this.f!=a.id;window.setTimeout(this.L.bind(this),30)};
g.pa=function(a){if(Enabler.isServingInLiveEnvironment())var b=a;else{if(!a.data||"string"!==typeof a.data)return;try{b=JSON.parse(a.data)}catch(c){return}if(b.eventType!==studio.events.StudioEvent.HOSTPAGE_SCROLL)return}D("hostpagescroll",this,b)};g.oa=function(){if(!this.f){var a=window.innerHeight>=window.innerWidth?1:2;this.I!=a&&(this.I=a,(a=this.a.getPage(this.a.currentIndex))&&window.setTimeout(this.goToPage.bind(this,a.id),0))}};g.ia=function(a){a&&Enabler.setResponsiveSize(a.width,a.height)};
g.L=function(){if(this.f){this.I=window.innerHeight>=window.innerWidth?1:2;var a=this.a.getOrientationSpecificPage(this.I,this.f);this.m?this.a.goToPage(a.id,this.m.transition,this.m.duration,this.m.easing,this.m.direction):this.a.goToPage(a.id);this.l&&a.classList.add("fs")}this.m=this.f=void 0};
g.na=function(a){this.v=this.w=!1;if(a.target==this.a){var b=a.detail;a=b.outgoingPage;b=b.incomingPage;if(a){var c=this.W;if(a.nodeType==Node.ELEMENT_NODE)for(var d=w(c.j),e=0;e<d.length;e++){var f=C(d[e]);if(f&&y(a,f))for(var m=x(c.j,d[e]),E=0;E<m.length;E++)f.removeEventListener(m[E].event,c.H,!1)}if((a=a.querySelectorAll("video, gwd-video"))&&0<a.length)for(this.O=[];this.N.length;)studio.video.Reporter.detach(this.N.shift())}this.W.observe(b);(a=b.querySelectorAll("video, gwd-video"))&&0<a.length&&
(b=studio.video&&studio.video.Reporter,c=this.ta.bind(this),this.O=Array.prototype.slice.call(a),b?c():Enabler.loadModule(studio.module.ModuleId.VIDEO,c))}};g.ta=function(){for(var a,b;this.O.length;)if(b=this.O.shift(),a=R(b))studio.video.Reporter.attach(a,"gwd-video"==b.tagName.toLowerCase()?b.nativeElement:b,b.autoplay),this.N.push(a)};
var R=function(a){return"object"==typeof gwd&&"GwdId"in gwd?(new gwd.GwdId(a)).getString():"string"==typeof a?a:a.id},S=function(a){a=Array.prototype.slice.call(a.a.querySelectorAll("audio, video, gwd-video, gwd-youtube, gwd-youtube-livestream, gwd-audio"));for(var b=0;b<a.length;b++)a[b].pause()};customElements.define("gwd-google-ad",N);}).call(this);
