(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},h;if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var l={B:!0},m={};try{m.__proto__=l;k=m.B;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=h,p=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},q=p(this);var r=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},t=function(a){if(r(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&r(a))return a;return null},u=function(a,b){return b!=a.getAttribute("source")?(a.setAttribute("source",b),!0):!1};var v=function(a,b){var c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)},w=function(a,b,c){var d=function(f){a.removeEventListener(b,d);c(f)};a.addEventListener(b,d)};var x=function(){this.v=""};x.prototype.toString=function(){return"SafeScript{"+this.v+"}"};x.prototype.b=function(a){this.v=a};(new x).b("");var y=function(a){return/^[\s\xa0]*$/.test(a)};var z=function(){this.A=""};z.prototype.toString=function(){return"SafeStyle{"+this.A+"}"};z.prototype.b=function(a){this.A=a};(new z).b("");var A=function(){this.w=""};A.prototype.toString=function(){return"SafeStyleSheet{"+this.w+"}"};A.prototype.b=function(a){this.w=a};(new A).b("");var B=function(){this.u=""};B.prototype.toString=function(){return"SafeHtml{"+this.u+"}"};B.prototype.b=function(a){this.u=a};(new B).b("<!DOCTYPE html>");(new B).b("");(new B).b("<br>");var C={G:"alignment",H:"bgcolor",I:"disabled",J:"down-image",K:"over-image",L:"scaling",M:"up-image"},D=[],E=0,F;for(F in C)D[E++]=C[F];var G=function(){var a=HTMLElement.call(this)||this;a.f="gwd_imagebutton_"+(2147483648*Math.random()|0);a.a=null;a.j=null;a.c=!1;a.s=!1;a.l=document.createElement("gwd-image");a.i=document.createElement("gwd-image");a.g=document.createElement("gwd-image");a.m=document.createElement("gwd-page");a.o=a.C.bind(a);a.F=a.D.bind(a);a.h=!1;return a},H=HTMLElement;
G.prototype=e(H.prototype);G.prototype.constructor=G;if(n)n(G,H);else for(var I in H)if("prototype"!=I)if(Object.defineProperties){var J=Object.getOwnPropertyDescriptor(H,I);J&&Object.defineProperty(G,I,J)}else G[I]=H[I];
G.prototype.connectedCallback=function(){if(!this.h){for(var a;a=this.firstChild;)this.removeChild(a);this.a=document.createElement("div");this.a.className=this.f;this.appendChild(this.a);this.style.display="inline-block";this.style.padding=0;this.a.style.backgroundRepeat="no-repeat";this.a.style.width="100%";this.a.style.height="100%";this.h=!0;a=["bgcolor","alignment","scaling","disabled"];for(var b=0;b<a.length;b++){var c=a[b];this.attributeChangedCallback(c,null,this.getAttribute(c),null)}}this.a.addEventListener("click",
this.o,!1);this.gwdIsLoaded()||((a=t(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad())};G.prototype.disconnectedCallback=function(){this.a.removeEventListener("click",this.o,!1)};
G.prototype.attributeChangedCallback=function(a,b,c){if(this.h)switch(a){case "alignment":c?this.a.style.backgroundPosition=c:this.setAttribute(a,"center");break;case "scaling":c?this.a.style.backgroundSize=c:this.setAttribute(a,"auto");break;case "up-image":K(this,this.l,c||"");break;case "over-image":K(this,this.i,c||"");break;case "down-image":K(this,this.g,c||"");break;case "disabled":this.c=this.hasAttribute("disabled")&&"false"!=this.getAttribute("disabled");L(this);this.a.style.cursor=this.c?
"default":"pointer";break;case "bgcolor":this.a.style.backgroundColor=c&&!y(c)?c:""}};var K=function(a,b,c){y(c)?L(a):(b.setAttribute("source",c),a.h&&M(a))};G.prototype.gwdIsLoaded=function(){return this.s};G.prototype.gwdLoad=function(){M(this)};
var M=function(a,b,c,d){b=b?b:a.getAttribute("up-image");c=c?c:a.getAttribute("over-image");d=d?d:a.getAttribute("down-image");var f=document.createElement("gwd-page");f.style.display="none";var g=!1;g=u(a.l,b||"")||g;g=u(a.i,c||"")||g;if(g=u(a.g,d||"")||g)f.appendChild(a.l),f.appendChild(a.i),f.appendChild(a.g),a.m=f,w(f,"attached",f.gwdLoad.bind(f)),w(f,"pageload",a.F),a.a.appendChild(a.m)};
G.prototype.D=function(a){if(a){a=a.target;a===this.m&&(this.s=!0,L(this),v("ready",this),v("imagebuttonloaded",this));var b=a.parentNode||a.parentElement;b&&b.removeChild(a)}};G.prototype.C=function(a){this.c&&a.stopPropagation()};
var L=function(a){if(a.j){var b=a.j;(b=b.ownerNode||b.owningElement||b)&&b.parentNode&&b.parentNode.removeChild(b);a.j=null}b="";var c=a.l.getAttribute("source");y(c)||(b+="."+a.f+' { background-image: url("'+c+'"); }');a.c||(c=a.i.getAttribute("source"),y(c)||(b+="."+a.f+':hover { background-image: url("'+c+'"); }'),c=a.g.getAttribute("source"),y(c)||(b+="."+a.f+':active { background-image: url("'+c+'"); }'));var d=document;c=d.getElementsByTagName("head")[0];if(!c){var f=d.getElementsByTagName("body")[0];
c=d.createElement("head");f.parentNode.insertBefore(c,f)}d=d.createElement("style");d.textContent=b;c.appendChild(d);a.j=d};G.prototype.toggleEnable=function(){(this.c=!this.c)?this.setAttribute("disabled","true"):this.removeAttribute("disabled")};G.prototype.setImages=function(a,b,c){M(this,a,b,c)};q.Object.defineProperties(G,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return D}}});customElements.define("gwd-imagebutton",G);}).call(this);
